name: Go dispatch

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: string
env:
  ENV_TEST: env_test

jobs:

  build:
    runs-on: ubuntu-latest
    environment: env_test01
    env:
      BUILD_ENV_TEST: ${{vars.VAR_TEST01}}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Test echo
      run: echo "Deploying to ${{ inputs.environment }} ${{secrets.GITHUB_TOKEN}}"

    - name: test env
      run: echo "Env test var ${{vars.VAR_TEST01}} env $ENV_TEST $BUILD_ENV_TEST"
